import * as React from "react"
import {
  CircleAlert,
  CircleCheck,
  Info,
  ShieldCheck,
  Sparkles,
  TriangleAlert,
  type LucideIcon,
} from "lucide-react"

import { cn } from "@/lib/utils"

/**
 * Notice — DESIGN_SYSTEM.md §5.17. One banner primitive, replacing the six hand-rolled
 * amber boxes and the `Alert variant="destructive"` that was abused for non-errors.
 *
 * ─────────────────────────────────────────────────────────────────────────────────────
 * WHY `tone="ai" as="note"` IS A SEPARATE SHAPE, AND WHY IT IS TYPED THIS WAY
 * ─────────────────────────────────────────────────────────────────────────────────────
 * The EU AI Act Art. 50 marking is a CONTINUOUS obligation: the user may not be able to
 * dismiss, collapse or hide the notice that says the text they are reading was generated by
 * a machine. `DraftSummaryView.transparency.test.tsx` already pins that as behaviour —
 * "the banner contains no control that hides it" — but a test only catches the mistake
 * after someone makes it, and the mistake is one line (`action={<Button>Dismiss</Button>}`).
 *
 * So the guard is STRUCTURAL here, in the type and in the renderer:
 *
 *   1. `AiNoteProps` declares `action?: never`, so passing an action to the marking is a
 *      compile error, not a review comment.
 *   2. Its `children` (and `title`) go through `toPlainText()`, which keeps strings and
 *      numbers and DROPS every element. A `<button>`, a `[role=button]` or an `<input>`
 *      handed to it cannot reach the DOM — the banner renders their text, or nothing.
 *
 * This is the SINGLE `role="note"` per surface. The four frozen names that consume it:
 *   🔒 `AI-generated content, human review required`  (ReviewRequiredBanner, all four
 *      DraftSummaryView states)
 *   🔒 `You are interacting with an AI assistant; AI-generated content, human review
 *      required`  (the AskPanel disclosure)
 *   🔒 `AI-generated content notice`  (CopilotInsights' AiMarking)
 *   🔒 `Legacy AI-generated summary is unverified`  (the legacy-summary banner)
 *
 * The per-card chip is NOT this component: `report/primitives.tsx`'s `AiLabel` is a plain
 * `<span>` with no role and no aria-label (§0.3 item 1). Giving the chip `role="note"` and
 * the banner's name puts two `note`s with the same accessible name inside one tree, and the
 * transparency suite's SINGULAR `getByRole('note', { name: … })` throws on the second one.
 *
 * WHY THE ICON IN THE `note` BRANCH CARRIES NO `aria-hidden`: §8 requires the marking to
 * have no descendant that is a `button`, `[role=button]`, `input`, `aria-hidden` or
 * `hidden`. The shipped `ReviewRequiredBanner` already renders its icon unhidden; the
 * marking is a thing that must never be partially hidden from AT, so nothing inside it is.
 * Every other tone hides its icon, which is decorative next to a visible title.
 *
 * TONES. `consent` is the one tone §5.17 names without giving it tokens. It takes the
 * `--verified` register ("a human decided", §0.2 P1) with a `ShieldCheck`, because the
 * consent-responsibility box is a statement about a human's duty, not a warning that
 * something is wrong — and `warning` amber is reserved for things that ARE wrong (§5.8).
 * Every ink-on-tint pair below is certified ≥5.6:1 in both themes in §4.4.3.
 */
export type NoticeTone =
  | "info"
  | "warning"
  | "success"
  | "destructive"
  | "ai"
  | "consent"

const TONE: Record<NoticeTone, { box: string; defaultIcon: LucideIcon }> = {
  info: { box: "border-info-border bg-info-surface text-info-ink", defaultIcon: Info },
  warning: {
    box: "border-warning-border bg-warning-surface text-warning-ink",
    defaultIcon: TriangleAlert,
  },
  success: {
    box: "border-success-border bg-success-surface text-success-ink",
    defaultIcon: CircleCheck,
  },
  destructive: {
    box: "border-destructive-border bg-destructive-surface text-destructive-ink",
    defaultIcon: CircleAlert,
  },
  ai: { box: "border-ai-border bg-ai-surface text-ai-ink", defaultIcon: Sparkles },
  consent: {
    box: "border-verified-border bg-verified-surface text-verified-ink",
    defaultIcon: ShieldCheck,
  },
}

interface NoticeBase {
  /** `text-body`, medium. The one-line statement. */
  title?: React.ReactNode
  children?: React.ReactNode
  /** Pass `null` to render no icon. Defaults to the tone's icon. */
  icon?: LucideIcon | null
  className?: string
  id?: string
}

/**
 * The Art. 50 marking. `as="note"` is only reachable with `tone="ai"`, it REQUIRES the
 * frozen accessible name, and it accepts no action.
 */
export interface AiNoteProps extends NoticeBase {
  tone: "ai"
  as: "note"
  /** 🔒 One of the four frozen names above — this is what AT reads. */
  "aria-label": string
  title?: string
  /** Structurally forbidden: the marking may never carry a control (§5.17). */
  action?: never
}

export interface StandardNoticeProps extends NoticeBase {
  tone?: NoticeTone
  /** `status` for a live region (🔒 TrialBanner, 🔒 EncryptionStatusBanner). */
  as?: "div" | "status"
  action?: React.ReactNode
  "aria-label"?: string
  "aria-live"?: "off" | "polite"
}

export type NoticeProps = AiNoteProps | StandardNoticeProps

/**
 * The text-only renderer. Elements are dropped, not unwrapped-and-rendered: that is what
 * makes "contains no control" a property of the component instead of a promise.
 *
 * Exported because the per-card `AiLabel` (`report/primitives.tsx`) needs the same guard for
 * the same reason — it is the other half of the Art. 50 marking, and it must not be able to
 * grow a control either.
 */
export function toPlainText(node: React.ReactNode): string {
  if (node === null || node === undefined || typeof node === "boolean") return ""
  if (typeof node === "string") return node
  if (typeof node === "number") return String(node)
  if (Array.isArray(node)) return node.map(toPlainText).join("")
  if (React.isValidElement(node)) {
    return toPlainText((node.props as { children?: React.ReactNode }).children)
  }
  return ""
}

export function Notice(props: NoticeProps) {
  const { title, children, icon, className, id } = props
  const tone: NoticeTone = props.tone ?? "info"
  const isAiNote = props.as === "note"
  const Icon = icon === null ? null : (icon ?? TONE[tone].defaultIcon)

  const body = isAiNote ? toPlainText(children) : children
  const heading = isAiNote ? toPlainText(title) : title
  const action = isAiNote ? null : props.action
  const role = isAiNote ? "note" : props.as === "status" ? "status" : undefined

  return (
    <div
      id={id}
      role={role}
      aria-label={props["aria-label"]}
      aria-live={isAiNote ? undefined : props["aria-live"]}
      className={cn(
        "flex w-full items-start gap-2 rounded-md border p-3",
        TONE[tone].box,
        className
      )}
    >
      {Icon ? (
        <Icon
          className="mt-0.5 size-4 shrink-0"
          // See the docblock: the marking hides nothing from AT.
          aria-hidden={isAiNote ? undefined : true}
        />
      ) : null}
      <div className="min-w-0 flex-1 space-y-0.5">
        {heading ? <p className="text-body font-medium">{heading}</p> : null}
        {body ? <div className="text-caption">{body}</div> : null}
      </div>
      {action ? (
        <div className="ml-2 flex shrink-0 items-center gap-2">{action}</div>
      ) : null}
    </div>
  )
}
Notice.displayName = "Notice"
